<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByUser(User $user) {

        $qb = $this->createQueryBuilder('t')
            ->where('t.id_user > :id')
            ->setParameter('id', $user->getId())
            ->getQuery();

        return $qb->execute();
    }
}
