app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

todo:
    path:     /todo
    defaults: { _controller: AppBundle:Todo:index }